export const ADDCAR = 'ADDCAR';
export const CARFAILED = 'CARFAILED';
export const LOADINGCAR = 'LOADINGCAR';
export const ADDCARNAME = 'ADDCARNAME';
export const FAILEDTOGETCARNAME = 'FAILEDTOGETCARNAME';
export const LOADINGCARCOMPANYNAME = 'LOADINGCARCOMPANYNAME';